name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      rttys_version: ${{ steps.get-rttys-version.outputs.RttysVersion }}
    steps:
      - uses: actions/checkout@v4

      - id: get-version
        uses: battila7/get-version-action@v2
        # Removed with: strip-suffix: "_ko"

      - name: Get RttysVersion from main.go
        id: get-rttys-version
        run: echo "RttysVersion=$(grep 'const RttysVersion' main.go | cut -d'"' -f2)" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build ui
        run: |
          cd ui
          npm install
          npm run build
          cd ..

      - name: Build rttys release
        run: |
          sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          ./build-deb.sh amd64
          ./build-deb.sh arm64
          COMPRESS=1 ./build.sh linux amd64
          COMPRESS=1 ./build.sh linux arm64
          COMPRESS=1 ./build.sh windows amd64
          ./build.sh linux amd64

      - name: Prepare rttys binary for artifact
        run: cp rttys-${{ steps.get-rttys-version.outputs.RttysVersion }}-linux-amd64/rttys rttys

      - name: Upload rttys binary
        uses: actions/upload-artifact@v4
        with:
          name: rttys-binary
          path: rttys

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rttys_${{ steps.get-rttys-version.outputs.RttysVersion }}_amd64.deb
            rttys_${{ steps.get-rttys-version.outputs.RttysVersion }}_arm64.deb
            rttys-${{ steps.get-rttys-version.outputs.RttysVersion }}-linux-amd64.tar.bz2
            rttys-${{ steps.get-rttys-version.outputs.RttysVersion }}-linux-arm64.tar.bz2
            rttys-${{ steps.get-rttys-version.outputs.RttysVersion }}-windows-amd64.tar.bz2
          draft: true

  docker:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4

      - id: get-version
        uses: battila7/get-version-action@v2
        # Removed with: strip-suffix: "_ko"

      - name: Download rttys binary
        uses: actions/download-artifact@v4
        with:
          name: rttys-binary

      - name: Make rttys executable
        run: chmod +x rttys

      - uses: docker/login-action@v3
        with:
          username: jkhkr
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jkhkr/rttys:${{ needs.build.outputs.rttys_version }},jkhkr/rttys:latest